### ISSUE TITLE
Error while reconstructing Knee Dataset

### ISSUE THREAD

**Issue by hkaggarwal** [mikgroup/mridata#14]
Hi,
I am trying to reconstruct the Stanford fully sampled 3D FSE Knee dataset listed on mridata.org with
UUID= as 52c2fd53-d233-4444-8bfd-7c454240d314

The Matlab script named test_recon_dataset.m at the location https://github.com/ismrmrd/ismrmrd/tree/master/examples/matlab gives the following error at line 142:
"Subscript indices must either be real positive integers or logicals."
                ind1 = floor((enc_Nx - rec_Nx)/2)+1; 
                ind2 = floor((enc_Nx - rec_Nx)/2)+rec_Nx; 
                im = K(ind1:ind2,:,:,:);
While debugging I am getting ind1=-95 and ind2=416, therefore, it is giving error at next line due to negative indices. I am not sure about how to fix it.

Can you please help me resolve this issue. 
Or which script should I use to reconstruct the knee datasets?

Thanks,
Hemant

**Comment by frankong** [comment]
I'd be happy to help, but have a deadline next Friday. I'll be able to help after that.

**Comment by hkaggarwal** [comment]
Sure, will wait and keep trying myself. Thanks.

**Comment by RanMaosong** [comment]
> Sure, will wait and keep trying myself. Thanks.

Do you solve this proplem?

**Comment by hkaggarwal** [comment]
@RanMaosong, I could not find a way to solve it. I am hoping @frankong will have some suggestions to try.

**Comment by frankong** [comment]
Sorry for the late reply. The error occurs because the ISMRMRD demo recon script tries to crop the image to the specified recon image size. This is often useful for Siemens data because the readout direction is oversampled by 2, so the direct ifft result is 2x zero-padded and cropping makes sense. On the other hand, the recon image size specified in GE data refers to the interpolated image size, which is bigger. The simplest way to modify the demo script is to remove the cropping. 

Here's the modified script that I managed to recon the knee dataset successfully:
https://gist.github.com/frankong/cae55ce8aa5be3a02f3c95a89ed6a569
<img width="447" alt="screen shot 2019-01-02 at 2 09 30 pm" src="https://user-images.githubusercontent.com/9143405/50615413-457b3b80-0e99-11e9-910a-a7eb8e8d25d3.png">

**Comment by hkaggarwal** [comment]
Thanks, @frankong, it is helpful.
