### ISSUE TITLE
User login, no batch download button

### ISSUE THREAD

**Issue by zwep** [mikgroup/mridata#19]
After a user login, and applying the following search critera

uploader: jycheng

It found 89 datasets. Great! But I can't seem to download all of these in one go. I expected that the Batch Download button would pop up and provide this functionality. Since the FAQ mention something about this.

Am I wrong? Did I something wrong? Is it better to just scrape the UUID's from the search, and download them with (in my case) Python?

**Comment by frankong** [comment]
Sorry for the late response.
The best way to batch download right now is to use the python command line tool:
https://pypi.org/project/mridata/

You can install it using `pip install mridata`. The command line tool supports batch downloading datasets with UUIDs. Internally, it basically does a for loop and download the urls with the uuid filled in.

This is still under development. There was a `Download UUIDs` button before, but it was removed because of a bug introduced. I hope to add it back in soon.

**Comment by zwep** [comment]
Great, thanks for that one!

**Comment by zwep** [comment]
Btw, here is a piece of code that helps to GET all the UUIDs ;)

> 
> import mridata
> from bs4 import BeautifulSoup as bs
> import bs4.element
> import re
> import itertools
> import os
> 
> 
> file_dir = r'path\to\files'
> #### Contains the fully loaded html page
> search_file = os.path.join(file_dir, 'search_file.txt')
> uuid_file = os.path.join(file_dir, 'uuid_file.txt')
> 
> with open(search_file, 'r', encoding='utf-8') as f:
>     A = f.read()
> 
> res_text_file = bs(A, 'lxml')
> 
> a_start = res_text_file.findAll("tr")
> temp_uuid = []
> for i_line in a_start:
>     # Filter on Tag elements
>     content_list = [x.contents for x in i_line.contents if type(x) == bs4.element.Tag]
>     content_list = list(itertools.chain(*content_list))
>     # Check for UUID content
>     if 'UUID' in content_list:
>         temp_uuid.append(content_list)
> 
> re_uuid = re.compile('\w+-\w+-\w+-\w+-\w+')
> uuid_list = list(set([x[1] for x in temp_uuid if re_uuid.match(x[1])]))
> 
> ####  Stores the file with UUID's
> with open(uuid_file, 'w') as f:
>     f.write('\n'.join(uuid_list))
> 
> for i_uuid in uuid_list:
>     mridata.download(i_uuid, file_dir)

Here I copied the html from the fully loaded webpage. Because there is a Javascript function that does the dynamic loading, scraping it with only the url will only give you 10 results.
